name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.12.3 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Test
        run: pnpm test:ci
      - name: Build
        run: pnpm build
      - name: Build Docker images
        run: docker-compose build

  build-mobile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.12.3 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint mobile app
        run: pnpm --filter=trip-sync-mobile lint
      - name: Typecheck mobile app
        run: pnpm --filter=trip-sync-mobile type-check
      - name: Test mobile app
        run: pnpm --filter=trip-sync-mobile test
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  deploy:
    needs: [build, build-mobile]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.12.3 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and push to Coolify
        env:
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          docker-compose push
          curl -X POST \
            -H "Authorization: Bearer $COOLIFY_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"projectId": "your-project-id"}' \
            https://api.coolify.io/v1/projects/deploy
