name: Project Board Automation

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      projects: write

    steps:
      - name: Add to Sabron Trip Sync Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/learnednomad/projects/4
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: feature:auth,feature:itinerary,feature:visa,feature:cultural,feature:expense,feature:social,feature:maps,feature:booking,feature:safety,feature:offline,feature:analytics
          label-operator: OR

      - name: Set Priority Field
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            
            // Extract priority from labels
            const labels = context.payload.issue?.labels || context.payload.pull_request?.labels || [];
            const priorityLabel = labels.find(label => label.name.startsWith('priority:'));
            
            if (priorityLabel) {
              const priority = priorityLabel.name.replace('priority:', '');
              console.log(`Setting priority to: ${priority}`);
              
              // Note: Setting project field values requires additional GraphQL operations
              // This is a placeholder for more advanced project field automation
              // The priority information is already captured in the issue labels
            }

      - name: Set Phase Field
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            
            // Extract phase from labels
            const labels = context.payload.issue?.labels || context.payload.pull_request?.labels || [];
            const phaseLabel = labels.find(label => label.name.startsWith('phase:'));
            
            if (phaseLabel) {
              const phase = phaseLabel.name.replace('phase:', '');
              console.log(`Setting phase to: ${phase}`);
              
              // Note: Setting project field values requires additional GraphQL operations
              // This is a placeholder for more advanced project field automation
              // The phase information is already captured in the issue labels
            }

  auto-assign-to-backlog:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
      projects: write
    
    if: github.event.action == 'opened'
    
    steps:
      - name: Move New Items to Backlog
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('New issue/PR created - should be automatically added to Backlog column');
            console.log('This will be handled by built-in GitHub Projects automation');
            
            // The built-in "Item added to project" workflow in GitHub Projects
            // should automatically move new items to the Backlog column
            
            // For additional custom logic, GraphQL mutations would be needed here
            // to update project item status fields