name: Project Board Automation Simple

on:
  issues:
    types: [opened, closed, labeled, unlabeled]
  pull_request:
    types: [opened, closed, labeled, unlabeled, ready_for_review]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add to Project via GraphQL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            
            // Simple test to see if workflow starts
            console.log('🎯 Project automation workflow started successfully!');
            console.log('Event:', context.eventName);
            console.log('Action:', context.payload.action);
            
            if (context.payload.issue) {
              console.log('Issue:', context.payload.issue.number, context.payload.issue.title);
            }
            
            if (context.payload.pull_request) {
              console.log('PR:', context.payload.pull_request.number, context.payload.pull_request.title);
            }
            
            // TODO: Add actual project management GraphQL here once workflow starts properly