name: Quality Gates

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.12.3 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Approve build scripts
        run: pnpm approve-builds @prisma/client @prisma/engines esbuild prisma
      
      - name: ESLint Check
        run: pnpm lint
      
      - name: TypeScript Check
        run: pnpm typecheck
      
      - name: Security Audit
        run: pnpm audit --audit-level moderate
      
      - name: Dependency Check
        run: pnpm outdated || true
      
      - name: Bundle Size Check
        run: |
          pnpm build
          echo "Bundle sizes:"
          find apps/web/.next/static -name "*.js" -exec wc -c {} + | tail -1
          find apps/mobile/dist -name "*.js" -exec wc -c {} + | tail -1 || echo "Mobile bundle not found"

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.12.3 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Approve build scripts
        run: pnpm approve-builds @prisma/client @prisma/engines esbuild prisma
      
      - name: Run tests with coverage
        run: pnpm test:ci
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true