name: Test No Permissions Declaration

on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple test without permissions
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('✅ Workflow started without explicit permissions!');
            console.log('Testing if this avoids startup_failure...');