name: Test Add To Project Action

on:
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test actions/add-to-project minimal
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/learnednomad/projects/4
          github-token: ${{ secrets.PROJECT_TOKEN }}