name: Test PROJECT_TOKEN Access

on:
  workflow_dispatch: {}
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Test PROJECT_TOKEN exists
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            console.log('✅ PROJECT_TOKEN is accessible');
            console.log('Testing basic API access...');
            
            try {
              const user = await github.rest.users.getAuthenticated();
              console.log('✅ Authenticated as:', user.data.login);
              
              // Test basic repo access
              const repo = await github.rest.repos.get({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              console.log('✅ Repository access confirmed');
              
            } catch (error) {
              console.error('❌ Error:', error.message);
            }